AWSTemplateFormatVersion: "2010-09-09"
Description: Create some Stuff
Resources:
  MyRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyRepoName
      RepositoryDescription: a description
